### ISSUE TITLE
mp-ci preview怎么显示二维码？

### ISSUE THREAD

**Issue by XIAOGUIGUI** [ineo6/mp-ci-demo#1]
在Actions怎么配置mp-ci preview上传进行二维码显示？

**Comment by ineo6** [comment]
这个没有尝试过，`Actions`里面直接把二维码写入仓库，这个需要你自己处理下。另外也可以通过发送邮件、通知（企业微信、钉钉）方式，我觉得这样可能会好点。

**Comment by XIAOGUIGUI** [comment]
> 这个没有尝试过，`Actions`里面直接把二维码写入仓库，这个需要你自己处理下。另外也可以通过发送邮件、通知（企业微信、钉钉）方式，我觉得这样可能会好点。

嗯，这个也是对的，还有那个预览命令好像都没用，看了你的源代码，好像都不会进入那个2的
console.log(_a.label)
guideMacBook-Pro:mp-interesting gui$ mp-ci preview ./dist/wx/ --pkp=./private.key --qrDest=./gg/
0
5
